### ISSUE TITLE
Asus Xonar AE Mutiple Channels

### ISSUE THREAD

**Issue by amill206** [mahilab/Syntacts#6]
Hi, I'm using the xonar AE sound card and trying to output on all 8 channels, but we are only able to output on 2 at a time through 1 audio jack. when we plug in 4 audio jacks into the sound card, we can only get 1 of the jacks to work, which is the one that is set to the "default" on the pc.  

We output on 1 session :
session = Session()     

open the default device which is our soundcard -> we make it the default manually on our computer
session.open() 

then we create a signal:

sig1 = Sine(440) # a 440 Hz sinewave
print(sig1.length) # inf

Then we connect to all 8 channels and play
session.play(0, sig1)
session.play(1, sig1)
session.play(2, sig1)
session.play(3, sig1)
session.play(4, sig1)
session.play(5, sig1)
session.play(6, sig1)
session.play(7, sig1)

But it only outputs on channel 0 and 1

we also tried connecting like this:
session.open(1)

after finding our soundcard with the example.py script which told us it was on index 1

![image](https://user-images.githubusercontent.com/74028378/129491754-eaed8e0d-eee9-4c4d-a5a7-6a31c8ea893f.png)

 Do you have any suggestions on how to output on all 8 channels? I'm using a Dell Precision Tower 5810.

**Comment by epezent** [comment]
Hi, sometimes it takes a bit of tinkering to get these cards working properly. Here are a list of steps that I can recommend off the top of my head:

1. Install the [drivers from ASUS](https://www.asus.com/us/Motherboards-Components/Sound-Cards/Gaming/Xonar-AE/HelpDesk_Download/)
2. Once installed, prefer the ASIO driver instead of MME

Alternatively, you may be able to enable 7.1 output in Windows (we previously had to follow these steps for a similar device that didn't provide ASIO support):

1. Right click speaker icon in bottom right corner and click "Sounds"
2. Under the playback tab, find the sound card device, click once to highlight it
3. Click the configure button
4. Make sure 7.1 surround is highlighted
5. Click next and step through the rest according to your preferences and then hit finish

Hope one of these helps. FWIW, there is a way as this is one of the cards a remember explicitly testing. Note that I am no longer with the MAHI lab, and so someone internally would be required to assist your further. @gadzooks00, can assign someone in the lab to monitor this issue.

**Comment by amill206** [comment]
Hi, how do I prefer the ASIO driver instead of MME? This is what I downloaded 
![image](https://user-images.githubusercontent.com/74028378/129637924-c574e4ef-57d5-4266-bc57-7ee000bc4053.png)

**Comment by gadzooks00** [comment]
@epezent thanks for the initial response. I can troubleshoot a bit with them from here.

After you have installed drivers and are connected to the device you should see multiple indices corresponding to the card including various APIs. Select the index corresponding to the ASIO API for the card if possible. 

Once you have installed drivers, it would be helpful to see any output you might have on what devices you are able to see. @amill206

**Comment by epezent** [comment]
![image](https://user-images.githubusercontent.com/29577475/129649656-40d11067-6f45-42c6-b856-f06578691051.png)

In the example above, one device (a MOTU 24Ao) can be driven using 5 different backend API (MME, WDM-KS, DirectSound, WASAPI, and ASIO). As far as Syntacts is concerned, each of this is a different "device", and assigned a separate index. You need to find the index that is for your device using the ASIO API. If for some reason you don't see an ASIO option after installing the driver, you can try some of the other APIs your hardware supports. MME isn't typically a great option for 2+ channel support. Always prefer ASIO if it's available. DirectSound is ok too.

**Comment by amill206** [comment]
So this is the desired index with ASIO 
![image](https://user-images.githubusercontent.com/74028378/129731097-46b76666-9677-4130-9aa6-d06d9b093f3c.png)

but when I change the code to:
session.open(8)

**Comment by gadzooks00** [comment]
@amill206 Please link to or reference the code you are referring to where you construct and open the session.

**Comment by amill206** [comment]
[example_basic.zip](https://github.com/mahilab/Syntacts/files/7001470/example_basic.zip)
Here is the edited example_basic code @gadzooks00

**Comment by gadzooks00** [comment]
Your code seems fine. If the only issue is the default device, you should be able to set that by changing your default audio device in your sound settings. Just right click the speaker icon, select sounds and then choose the xonar device right click and set as default.

**Comment by amill206** [comment]
@gadzooks00 Yeah the card is set to the default device 
![image](https://user-images.githubusercontent.com/74028378/129801851-51311522-e44e-468c-9e07-7ff568b51ea0.png)
 I'm not sure how it specifies which is MME and which is ASIO.

**Comment by epezent** [comment]
You generally don't have the ability to choose the device API from the Windows interface. This isn't something your typical Windows user is going to care about, and usually only DAWs (or specialty software like Syntacts) expose these options for sound cards

I do not recommend what you are trying to do, anyway. Why not just call `session.open(8)`? If you're concerned about the index changing in the future, then use one of the other overloads of `open`, e.g. name+api or just api:

https://github.com/mahilab/Syntacts/blob/cae3eb0fa6aca34bde4ccacbd943c038a9ae1d7e/python/syntacts.py#L117-L125

**Comment by amill206** [comment]
> You generally don't have the ability to choose the device API from the Windows interface. This isn't something your typical Windows user is going to care about, and usually only DAWs (or specialty software like Syntacts) expose these options for sound cards
> 
> I do not recommend what you are trying to do, anyway. Why not just call `session.open(8)`? If you're concerned about the index changing in the future, then use one of the other overloads of `open`, e.g. name+api or just api:
> 
> https://github.com/mahilab/Syntacts/blob/cae3eb0fa6aca34bde4ccacbd943c038a9ae1d7e/python/syntacts.py#L117-L125

Hi we did try the session.open(8) but it only plays out of channel 0 and 1 . The code we used is linked above. We have tested all 8 speakers through the PC and they work.

**Comment by amill206** [comment]
@epezent  @gadzooks00 Thanks for your help. We got it to work after we just opened all the channels to try it. Strangely, channels 2/3 wouldn't work in conjunction with 0/1 unless 3/4 were also plugged in. Additionally, channels 2&4 and 3&5 are flipped.

**Comment by gadzooks00** [comment]
That is strange but I am glad to hear you have gotten it working. I am closing this issue then.
